# -*- coding: utf-8 -*-
"""Spinny Kitty Spinning Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R49ilYCfoFYy3VuJ1tbd7pQvCooijN18
"""

!pip install librosa --quiet

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from IPython.display import Audio
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

AUDIO_FILE = "OIIA.mp3"

y, sr = librosa.load(AUDIO_FILE, sr=None)
duration = librosa.get_duration(y=y, sr=sr)

print(f"Loaded: {AUDIO_FILE}")
print(f"Duration: {duration:.1f} seconds")
print(f"Sample rate: {sr} Hz")

Audio(y, rate=sr)

# --- APPROACH 1: Beat Tracking ---
# --- BEAT TRACKING ---
tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)
beat_times = librosa.frames_to_time(beat_frames, sr=sr)
tempo_value = float(tempo[0]) if hasattr(tempo, '__len__') else float(tempo)
print(f"Detected tempo: {tempo_value:.1f} BPM")

# --- ONSET DETECTION (sub-beat rhythms: drum hits, notes, etc.) ---
onset_frames = librosa.onset.onset_detect(y=y, sr=sr, wait=1, delta=0.05)
onset_times = librosa.frames_to_time(onset_frames, sr=sr)
print(f"Detected {len(onset_times)} onsets")

# --- RMS ENERGY (loudness over time) ---
hop_length = 512
rms = librosa.feature.rms(y=y, hop_length=hop_length)[0]
rms_times = librosa.frames_to_time(np.arange(len(rms)), sr=sr, hop_length=hop_length)

# Normalize RMS to 0.0 – 1.0
rms_norm = rms / rms.max()
# --- TUNABLE PARAMETERS ---
PWM_MIN = 40       # minimum motor speed (0-255). Keep above 0 so motor doesn't stall
PWM_MAX = 255      # maximum motor speed
BEAT_BOOST = 80    # extra PWM added on a beat hit (decays quickly)
ONSET_BOOST = 40   # extra PWM added on a sub-beat onset
DECAY = 0.85       # how quickly the boost fades each time step (0-1, lower = faster decay)

# --- BUILD PWM TIMELINE ---
# We'll compute one PWM value per RMS frame (~every 11ms at sr=22050)
pwm_values = np.zeros(len(rms_times))

for i, t in enumerate(rms_times):
    # Base speed from energy: maps 0.0-1.0 RMS to PWM_MIN-PWM_MAX
    base = PWM_MIN + rms_norm[i] * (PWM_MAX - PWM_MIN)
    pwm_values[i] = base

# Add beat boosts — spike PWM upward on each beat, then decay
for beat_t in beat_times:
    # Find the closest frame index to this beat time
    idx = np.argmin(np.abs(rms_times - beat_t))
    boost = BEAT_BOOST
    j = idx
    while j < len(pwm_values) and boost > 1:
        pwm_values[j] = min(PWM_MAX, pwm_values[j] + boost)
        boost *= DECAY
        j += 1

# Add onset boosts (smaller than beat boosts)
for onset_t in onset_times:
    idx = np.argmin(np.abs(rms_times - onset_t))
    boost = ONSET_BOOST
    j = idx
    while j < len(pwm_values) and boost > 1:
        pwm_values[j] = min(PWM_MAX, pwm_values[j] + boost)
        boost *= DECAY
        j += 1

# Clip to valid PWM range
pwm_values = np.clip(pwm_values, PWM_MIN, PWM_MAX)

print(f"PWM range in output: {pwm_values.min():.0f} – {pwm_values.max():.0f}")
fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)
fig.suptitle("Motor PWM Timeline", fontsize=14, fontweight='bold')

# --- Plot 1: Waveform with beat and onset markers ---
ax1 = axes[0]
librosa.display.waveshow(y, sr=sr, ax=ax1, color='steelblue', alpha=0.6)
for bt in beat_times:
    ax1.axvline(x=bt, color='red', linewidth=0.8, alpha=0.7)
for ot in onset_times:
    ax1.axvline(x=ot, color='orange', linewidth=0.5, alpha=0.4)
ax1.set_ylabel("Amplitude")
ax1.set_title("Waveform  |  red = beats   orange = onsets")
beat_patch = mpatches.Patch(color='red', label='Beats')
onset_patch = mpatches.Patch(color='orange', label='Onsets')
ax1.legend(handles=[beat_patch, onset_patch], loc='upper right', fontsize=8)

# --- Plot 2: RMS energy ---
ax2 = axes[1]
ax2.fill_between(rms_times, rms_norm, alpha=0.6, color='mediumseagreen')
ax2.set_ylabel("Normalized RMS")
ax2.set_title("Energy (loudness) — drives baseline motor speed")
ax2.set_ylim(0, 1.1)

# --- Plot 3: PWM output ---
ax3 = axes[2]
ax3.fill_between(rms_times, pwm_values, alpha=0.8, color='mediumpurple')
ax3.set_ylabel("PWM Value (0–255)")
ax3.set_title("Generated PWM Signal — motor speed over time")
ax3.set_ylim(0, 270)
ax3.set_xlabel("Time (seconds)")
ax3.axhline(y=PWM_MIN, color='gray', linestyle='--', linewidth=0.8, label=f'PWM_MIN ({PWM_MIN})')
ax3.legend(loc='upper right', fontsize=8)

plt.tight_layout()
plt.savefig("pwm_visualization.png", dpi=150, bbox_inches='tight')
plt.show()
print("Saved visualization to pwm_visualization.png")

"""NEW MOTOR GENERATION"""

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# =========================================================
# MOTOR PWM EXPORT FOR MSPM0
# Compact format:
#   #define DATA_COUNT ...
#   #define UPDATE_INTERVAL_MS 20
#   const uint8_t pwm_data[DATA_COUNT] = { ... };
# =========================================================

# ---------------------------------------------------------
# Load audio first if not already loaded
# y, sr = librosa.load(AUDIO_FILE, sr=None)
# ---------------------------------------------------------

# --- BEAT TRACKING ---
tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)
beat_times = librosa.frames_to_time(beat_frames, sr=sr)
tempo_value = float(tempo[0]) if hasattr(tempo, '__len__') else float(tempo)
print(f"Detected tempo: {tempo_value:.1f} BPM")

# --- ONSET DETECTION ---
onset_frames = librosa.onset.onset_detect(y=y, sr=sr, wait=1, delta=0.05)
onset_times = librosa.frames_to_time(onset_frames, sr=sr)
print(f"Detected {len(onset_times)} onsets")

# --- RMS ENERGY ---
hop_length = 512
rms = librosa.feature.rms(y=y, hop_length=hop_length)[0]
rms_times = librosa.frames_to_time(np.arange(len(rms)), sr=sr, hop_length=hop_length)

# Normalize RMS
rms_norm = rms / (rms.max() + 1e-9)

# ---------------------------------------------------------
# Tunable parameters
# ---------------------------------------------------------
PWM_MIN = 40       # minimum motor speed so it doesn't stall
PWM_MAX = 255      # maximum motor speed
BEAT_BOOST = 80    # stronger boost on beat
ONSET_BOOST = 40   # smaller boost on onset
DECAY = 0.85       # boost decay
FRAME_MS = 20      # compressed output time base for MSPM0

# ---------------------------------------------------------
# Build source PWM timeline at RMS-frame resolution
# ---------------------------------------------------------
pwm_values = np.zeros(len(rms_times), dtype=float)

# baseline from RMS energy
for i in range(len(rms_times)):
    base = PWM_MIN + rms_norm[i] * (PWM_MAX - PWM_MIN)
    pwm_values[i] = base

# beat boosts
for beat_t in beat_times:
    idx = np.argmin(np.abs(rms_times - beat_t))
    boost = BEAT_BOOST
    j = idx
    while j < len(pwm_values) and boost > 1:
        pwm_values[j] = min(PWM_MAX, pwm_values[j] + boost)
        boost *= DECAY
        j += 1

# onset boosts
for onset_t in onset_times:
    idx = np.argmin(np.abs(rms_times - onset_t))
    boost = ONSET_BOOST
    j = idx
    while j < len(pwm_values) and boost > 1:
        pwm_values[j] = min(PWM_MAX, pwm_values[j] + boost)
        boost *= DECAY
        j += 1

# clip valid range
pwm_values = np.clip(pwm_values, PWM_MIN, PWM_MAX)

print(f"Source PWM range: {pwm_values.min():.0f} – {pwm_values.max():.0f}")

# ---------------------------------------------------------
# Compress to fixed 20 ms time base
# ---------------------------------------------------------
duration_s = len(y) / sr
time_ms = np.arange(0, int(np.ceil(duration_s * 1000)) + FRAME_MS, FRAME_MS, dtype=int)
time_s = time_ms / 1000.0

# Interpolate PWM onto fixed time base
pwm_fixed = np.interp(time_s, rms_times, pwm_values)

# Optional smoothing to remove jitter
SMOOTH_FRAMES = 3
kernel = np.ones(SMOOTH_FRAMES) / SMOOTH_FRAMES
pwm_fixed = np.convolve(pwm_fixed, kernel, mode='same')

# Final integer PWM
pwm_fixed = np.clip(np.round(pwm_fixed), PWM_MIN, PWM_MAX).astype(np.uint8)

print("Compressed frame count:", len(pwm_fixed))
print("Compressed PWM range:", int(pwm_fixed.min()), "–", int(pwm_fixed.max()))
print("Approx storage bytes:", len(pwm_fixed))

# ---------------------------------------------------------
# Export to MSPM0 header
# ---------------------------------------------------------
with open("music_data.h", "w") as f:
    f.write("#ifndef MUSIC_DATA_H\n")
    f.write("#define MUSIC_DATA_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define DATA_COUNT ({len(pwm_fixed)}U)\n")
    f.write(f"#define UPDATE_INTERVAL_MS ({FRAME_MS}U)\n\n")
    f.write("const uint8_t pwm_data[DATA_COUNT] = {\n")

    for i, val in enumerate(pwm_fixed):
        if i % 16 == 0:
            f.write("    ")
        f.write(f"{int(val)}, ")
        if i % 16 == 15:
            f.write("\n")

    if len(pwm_fixed) % 16 != 0:
        f.write("\n")

    f.write("};\n\n")
    f.write("#endif\n")

print("Saved music_data.h")

# ---------------------------------------------------------
# Optional visualization
# ---------------------------------------------------------
fig, axes = plt.subplots(4, 1, figsize=(16, 12), sharex=True)
fig.suptitle("Compressed Motor PWM Timeline", fontsize=14, fontweight='bold')

# Plot 1: waveform with beat/onset markers
ax1 = axes[0]
librosa.display.waveshow(y, sr=sr, ax=ax1, color='steelblue', alpha=0.6)
for bt in beat_times:
    ax1.axvline(x=bt, color='red', linewidth=0.8, alpha=0.7)
for ot in onset_times:
    ax1.axvline(x=ot, color='orange', linewidth=0.5, alpha=0.4)
ax1.set_ylabel("Amplitude")
ax1.set_title("Waveform | red = beats | orange = onsets")
beat_patch = mpatches.Patch(color='red', label='Beats')
onset_patch = mpatches.Patch(color='orange', label='Onsets')
ax1.legend(handles=[beat_patch, onset_patch], loc='upper right', fontsize=8)

# Plot 2: RMS
ax2 = axes[1]
ax2.fill_between(rms_times, rms_norm, alpha=0.6, color='mediumseagreen')
ax2.set_ylabel("Normalized RMS")
ax2.set_title("Energy (loudness)")
ax2.set_ylim(0, 1.1)

# Plot 3: uncompressed source PWM
ax3 = axes[2]
ax3.fill_between(rms_times, pwm_values, alpha=0.8, color='mediumpurple')
ax3.set_ylabel("PWM")
ax3.set_title("Source PWM Timeline")
ax3.set_ylim(0, 270)

# Plot 4: compressed 20 ms PWM
ax4 = axes[3]
ax4.step(time_s, pwm_fixed, where='post', color='indigo', linewidth=1.0)
ax4.set_ylabel("PWM")
ax4.set_title("Compressed PWM Timeline (20 ms frames)")
ax4.set_ylim(0, 270)
ax4.set_xlabel("Time (seconds)")
ax4.axhline(y=PWM_MIN, color='gray', linestyle='--', linewidth=0.8, label=f'PWM_MIN ({PWM_MIN})')
ax4.legend(loc='upper right', fontsize=8)

plt.tight_layout()
plt.savefig("motor_pwm_compressed.png", dpi=150, bbox_inches='tight')
plt.show()

print("Saved motor_pwm_compressed.png")

# --- APPROACH 2: Pure RMS Energy Mapping ---
# No beat detection — motor speed follows loudness continuously

# Tunable parameters
A2_PWM_MIN = 40
A2_PWM_MAX = 255
A2_SMOOTHING = 15  # number of frames to smooth over (higher = more gradual changes)

# Smooth the RMS curve so the motor doesn't jitter on every tiny fluctuation
rms_smoothed = np.convolve(rms_norm, np.ones(A2_SMOOTHING)/A2_SMOOTHING, mode='same')

# Map smoothed RMS directly to PWM
pwm_approach2 = A2_PWM_MIN + rms_smoothed * (A2_PWM_MAX - A2_PWM_MIN)
pwm_approach2 = np.clip(pwm_approach2, A2_PWM_MIN, A2_PWM_MAX)

# --- Visualize ---
fig, axes = plt.subplots(2, 1, figsize=(16, 7), sharex=True)
fig.suptitle("Approach 2: RMS Amplitude Mapping", fontsize=14, fontweight='bold')

ax1 = axes[0]
librosa.display.waveshow(y, sr=sr, ax=ax1, color='steelblue', alpha=0.6)
ax1.set_ylabel("Amplitude")
ax1.set_title("Waveform")

ax2 = axes[1]
ax2.fill_between(rms_times, pwm_approach2, alpha=0.8, color='mediumseagreen')
ax2.plot(rms_times, pwm_approach2, color='darkgreen', linewidth=0.8, alpha=0.6)
ax2.set_ylabel("PWM Value (0–255)")
ax2.set_title("PWM Signal — smoothly follows loudness, no beat spikes")
ax2.set_ylim(0, 270)
ax2.set_xlabel("Time (seconds)")
ax2.axhline(y=A2_PWM_MIN, color='gray', linestyle='--', linewidth=0.8, label=f'PWM_MIN ({A2_PWM_MIN})')
ax2.legend(loc='upper right', fontsize=8)

plt.tight_layout()
plt.show()

# --- APPROACH 3: Frequency Band Mapping ---
# Split audio into bass / mids / highs and map each to motor behavior
# Bass energy → baseline speed, mids → small boost, highs → small boost

# Compute a mel spectrogram
hop_length = 512
n_mels = 128
S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels, hop_length=hop_length)
S_db = librosa.power_to_db(S, ref=np.max)

# Split mel bands into thirds (rough bass/mids/highs split)
bass_energy   = S[:n_mels//3, :].mean(axis=0)
mid_energy    = S[n_mels//3 : 2*n_mels//3, :].mean(axis=0)
high_energy   = S[2*n_mels//3:, :].mean(axis=0)

# Normalize each band to 0–1
def normalize(x):
    return (x - x.min()) / (x.max() - x.min() + 1e-9)

bass_norm  = normalize(bass_energy)
mid_norm   = normalize(mid_energy)
high_norm  = normalize(high_energy)

freq_times = librosa.frames_to_time(np.arange(S.shape[1]), sr=sr, hop_length=hop_length)

# Tunable parameters — weights for each band
A3_PWM_MIN   = 40
A3_PWM_MAX   = 255
BASS_WEIGHT  = 0.6   # bass has most influence on speed
MID_WEIGHT   = 0.25
HIGH_WEIGHT  = 0.15
A3_SMOOTHING = 10

# Weighted sum of bands → PWM
combined = (bass_norm * BASS_WEIGHT) + (mid_norm * MID_WEIGHT) + (high_norm * HIGH_WEIGHT)
combined_smoothed = np.convolve(combined, np.ones(A3_SMOOTHING)/A3_SMOOTHING, mode='same')
combined_norm = normalize(combined_smoothed)

pwm_approach3 = A3_PWM_MIN + combined_norm * (A3_PWM_MAX - A3_PWM_MIN)
pwm_approach3 = np.clip(pwm_approach3, A3_PWM_MIN, A3_PWM_MAX)

# --- Visualize ---
fig, axes = plt.subplots(5, 1, figsize=(16, 14), sharex=True)
fig.suptitle("Approach 3: Frequency Band Mapping", fontsize=14, fontweight='bold')

ax1 = axes[0]
librosa.display.waveshow(y, sr=sr, ax=ax1, color='steelblue', alpha=0.6)
ax1.set_ylabel("Amplitude")
ax1.set_title("Waveform")

ax2 = axes[1]
ax2.fill_between(freq_times, bass_norm, alpha=0.7, color='tomato')
ax2.set_ylabel("Normalized Energy")
ax2.set_title(f"Bass Energy  (weight: {BASS_WEIGHT})")
ax2.set_ylim(0, 1.1)

ax3 = axes[2]
ax3.fill_between(freq_times, mid_norm, alpha=0.7, color='goldenrod')
ax3.set_ylabel("Normalized Energy")
ax3.set_title(f"Mid Energy  (weight: {MID_WEIGHT})")
ax3.set_ylim(0, 1.1)

ax4 = axes[3]
ax4.fill_between(freq_times, high_norm, alpha=0.7, color='cornflowerblue')
ax4.set_ylabel("Normalized Energy")
ax4.set_title(f"High Energy  (weight: {HIGH_WEIGHT})")
ax4.set_ylim(0, 1.1)

ax5 = axes[4]
ax5.fill_between(freq_times, pwm_approach3, alpha=0.8, color='mediumpurple')
ax5.plot(freq_times, pwm_approach3, color='indigo', linewidth=0.8, alpha=0.6)
ax5.set_ylabel("PWM Value (0–255)")
ax5.set_title("PWM Signal — weighted blend of bass, mids, highs")
ax5.set_ylim(0, 270)
ax5.set_xlabel("Time (seconds)")
ax5.axhline(y=A3_PWM_MIN, color='gray', linestyle='--', linewidth=0.8, label=f'PWM_MIN ({A3_PWM_MIN})')
ax5.legend(loc='upper right', fontsize=8)

plt.tight_layout()
plt.show()

"""NEW LED EXPORT"""

# ── Paste this cell right after your loading cell ─────────────────────────────

import numpy as np
import librosa
import csv

# ── User-tuneable constants ───────────────────────────────────────────────────
OUT_CSV     = "led.csv"
NUM_LEDS    = 35
FRAME_DT_MS = 20        # must match binary packer — do not change
HOP_LENGTH  = 512       # analysis resolution
ONSET_DELTA = 0.18      # higher = fewer color changes

# Comet appearance
BRIGHT_MIN  = 40
BRIGHT_MAX  = 255
TAIL_MIN    = 2
TAIL_MAX    = 3
STEP_MIN    = 1
STEP_MAX    = 3

# Color palette — color_idx (0-7) stored in sparkle column
BEAT_PALETTE = [
    (255,   0,   0),
    (  0, 255,   0),
    (  0,   0, 255),
    (255, 165,   0),
    (128,   0, 255),
    (  0, 255, 200),
    (255, 255,   0),
    (255,  20, 147),
]

# ── Uses y, sr already loaded above ──────────────────────────────────────────

def normalize(x):
    return (x - x.min()) / (x.max() - x.min() + 1e-9)

# Energy
rms      = librosa.feature.rms(y=y, hop_length=HOP_LENGTH)[0]
rms_norm = normalize(rms)

# Onset detection
onset_frames = librosa.onset.onset_detect(
    y=y, sr=sr, hop_length=HOP_LENGTH,
    delta=ONSET_DELTA, units='frames'
)
onset_set = set(onset_frames.tolist())
print(f"Onsets detected: {len(onset_frames)}")

# ── Build full analysis-rate frame list ──────────────────────────────────────
analysis_dt_s   = HOP_LENGTH / sr
n_analysis      = len(rms_norm)
palette_idx     = 0
pos             = 0
analysis_frames = []   # (pos, bright, tail, color_idx)

for i in range(n_analysis):
    energy = float(rms_norm[i])

    if i in onset_set:
        palette_idx = (palette_idx + 1) % len(BEAT_PALETTE)

    step   = int(round(STEP_MIN + energy * (STEP_MAX - STEP_MIN)))
    bright = int(np.clip(BRIGHT_MIN + energy * (BRIGHT_MAX - BRIGHT_MIN), 0, 255))
    tail   = int(round(TAIL_MIN + energy * (TAIL_MAX - TAIL_MIN)))
    pos    = (pos + step) % NUM_LEDS

    analysis_frames.append((pos, bright, tail, palette_idx))

# ── Resample to exact 20 ms grid ─────────────────────────────────────────────
duration_s   = len(y) / sr
frame_dt_s   = FRAME_DT_MS / 1000.0
n_out_frames = int(duration_s / frame_dt_s)   # total 20 ms frames in song

rows = []
for f in range(n_out_frames):
    t_s          = f * frame_dt_s
    ana_idx      = int(round(t_s / analysis_dt_s))
    ana_idx      = min(ana_idx, n_analysis - 1)

    pos_v, bright_v, tail_v, cidx = analysis_frames[ana_idx]

    # Clamp to CSV spec ranges
    pos_v    = int(np.clip(pos_v,    0,  34))
    bright_v = int(np.clip(bright_v, 0, 255))
    tail_v   = int(np.clip(tail_v,   1,  35))
    sparkle  = int(np.clip(cidx,     0, 255))  # color_idx stored in sparkle

    rows.append((f * FRAME_DT_MS, pos_v, bright_v, tail_v, sparkle))

# ── Write CSV ─────────────────────────────────────────────────────────────────
with open(OUT_CSV, "w", newline="") as fh:
    writer = csv.writer(fh)
    writer.writerow(["time_ms", "pos", "bright", "tail_len", "sparkle"])
    writer.writerows(rows)

print(f"Saved: {OUT_CSV}")
print(f"  Frames:      {len(rows)}")
print(f"  Duration:    {len(rows) * FRAME_DT_MS / 1000:.1f} s")
print(f"  Frame dt:    {FRAME_DT_MS} ms")

# --- Compare all 3 approaches on the same time axis ---
# Resamples approach 3 to match the rms_times length if needed

from scipy.interpolate import interp1d

# Resample approach 3 PWM onto rms_times so all three align
interp_fn = interp1d(freq_times, pwm_approach3, bounds_error=False, fill_value="extrapolate")
pwm_a3_resampled = interp_fn(rms_times)

fig, axes = plt.subplots(3, 1, figsize=(16, 10), sharex=True)
fig.suptitle("All Approaches — PWM Comparison", fontsize=14, fontweight='bold')

labels = [
    ("Approach 1: Beat + Onset + Energy",  pwm_values,       'mediumpurple'),
    ("Approach 2: RMS Amplitude",           pwm_approach2,    'mediumseagreen'),
    ("Approach 3: Frequency Bands",         pwm_a3_resampled, 'tomato'),
]

for ax, (title, pwm, color) in zip(axes, labels):
    ax.fill_between(rms_times, pwm, alpha=0.5, color=color)
    ax.plot(rms_times, pwm, color=color, linewidth=1.0)
    ax.set_ylabel("PWM (0–255)")
    ax.set_title(title)
    ax.set_ylim(0, 270)
    ax.axhline(y=40, color='gray', linestyle='--', linewidth=0.7)

axes[-1].set_xlabel("Time (seconds)")
plt.tight_layout()
plt.show()

"""Extracting 10 second data"""

# --- EXPORT FOR MSPM0 ---
EXPORT_SECONDS = 10  # first 10s
FPS = int(1.0 / (hop_length / sr)) # 43 fps

# 10 sec data
test_pwm_data = pwm_values[:int(EXPORT_SECONDS * FPS)]

# convert 0-255 to 100% ratio
scaled_data = (test_pwm_data / 255.0 * 100).astype(int)

with open("music_data.h", "w") as f:
    f.write("#ifndef MUSIC_DATA_H\n#define MUSIC_DATA_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"// Data for {EXPORT_SECONDS} seconds at ~{FPS} FPS\n")
    f.write(f"#define DATA_COUNT {len(scaled_data)}\n")
    f.write(f"#define UPDATE_INTERVAL_MS {int(1000/FPS)}\n\n")
    f.write("const uint8_t pwm_data[] = {\n    ")

    for i, val in enumerate(scaled_data):
        f.write(f"{val}, ")
        if (i + 1) % 12 == 0:
            f.write("\n    ")

    f.write("\n};\n\n#endif")

print(f"Generated music_data.h with {len(scaled_data)} points.")

"""Making CSV file"""

OUTPUT_CSV = "motor.csv"
TARGET_INTERVAL_MS = 20  # 20ms frame

# 1. Computing RMS energy
# hop_length = sr * interval_sec
hop_length = int(sr * (TARGET_INTERVAL_MS / 1000.0))
rms = librosa.feature.rms(y=y, hop_length=hop_length)[0]

# 2. Normalizing RMS
rms_norm = rms / (rms.max() if rms.max() > 0 else 1)
motor_values = (rms_norm ** 2) * 255  # scale to 0-255

# 3. Make data frame
time_ms = np.arange(len(motor_values)) * TARGET_INTERVAL_MS
df = pd.DataFrame({
    'time_ms': time_ms.astype(int),
    'motor': motor_values.astype(int)
})

# 4. Save CSV
df.to_csv(OUTPUT_CSV, index=False)
print(f"Saved {len(df)} frames to {OUTPUT_CSV} (Duration: {duration:.2f}s)")